name-template: 'uat-v$NEXT_PATCH_VERSION'
tag-template: 'uat-v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels: ['feat', 'feature']
  - title: '🐛 Bug Fixes'
    labels: ['fix']
  - title: '🧹 Maintenance'
    labels: ['chore', 'refactor']
  - title: '⚠️ Breaking Changes'
    labels: ['breaking']

change-template: '- $TITLE (#$NUMBER)'

template: |
  ## Changes

  $CHANGES

  [Compare changes](https://github.com/$OWNER/$REPO/compare/$PREVIOUS_TAG...$TAG)
