name: Draft UAT Release

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
